# Generated by Django 5.2.8 on 2025-11-20 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=12, unique=True)),
                ('NombreE', models.CharField(max_length=50)),
                ('ApellidoE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreS', models.CharField(max_length=50)),
                ('CapacidadM', models.IntegerField()),
                ('Disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHI', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaHT', models.DateTimeField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.estudiante')),
                ('Sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.sala')),
            ],
        ),
    ]
